Imports System.Data.Odbc
Imports System.Data.SqlClient

Public Class Form2

    Private Sub Form2_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        ComboBox2.SelectedIndex = 3
        ComboBox3.SelectedIndex = Form3.ComboBox5.SelectedIndex
        ComboBox4.SelectedIndex = Form3.ComboBox6.SelectedIndex
        TextBox1.Text = Form3.TextBox3.Text
        TextBox2.Text = Form3.TextBox1.Text
        TextBox4.Text = Form3.TextBox7.Text
        TextBox5.Text = Form3.TextBox8.Text
        TextBox12.Text = Form3.TextBox24.Text

    End Sub

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click

        Try
            ' Create method of writing item values into text.
            Dim objWriter As New System.IO.StreamWriter(Application.StartupPath & "/Item_Ext.txt", True)
            'Item_ext Line +0
            objWriter.WriteLine(TextBox13.Text & "_" & TextBox1.Text & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox18.Text & "_" & TextBox19.Text & "_" & TextBox20.Text & "_" & TextBox21.Text & "_" & TextBox22.Text & "_" & TextBox23.Text & "_" & TextBox24.Text & "_" & TextBox25.Text & "_" & TextBox26.Text & "_" & TextBox27.Text & "_" & TextBox28.Text & "_" & TextBox29.Text & "_" & TextBox30.Text & "_" & TextBox31.Text & "_" & TextBox9.Text & "_" & TextBox32.Text & "_" & TextBox33.Text & "_" & TextBox34.Text & "_" & TextBox35.Text & "_" & TextBox36.Text & "_" & TextBox37.Text & "_" & TextBox38.Text & "_" & TextBox39.Text & "_" & TextBox40.Text & "_" & TextBox41.Text & "_" & TextBox42.Text & "_" & TextBox43.Text & "_" & TextBox44.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +1
            objWriter.WriteLine(TextBox60.Text & "_" & TextBox1.Text & " (+1)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox55.Text & "_" & TextBox54.Text & "_" & TextBox53.Text & "_" & TextBox52.Text & "_" & TextBox51.Text & "_" & TextBox50.Text & "_" & TextBox49.Text & "_" & TextBox48.Text & "_" & TextBox47.Text & "_" & TextBox46.Text & "_" & TextBox45.Text & "_" & TextBox220.Text & "_" & TextBox219.Text & "_" & TextBox218.Text & "_" & TextBox9.Text & "_" & TextBox217.Text & "_" & TextBox216.Text & "_" & TextBox215.Text & "_" & TextBox214.Text & "_" & TextBox213.Text & "_" & TextBox212.Text & "_" & TextBox211.Text & "_" & TextBox210.Text & "_" & TextBox209.Text & "_" & TextBox208.Text & "_" & TextBox207.Text & "_" & TextBox206.Text & "_" & TextBox205.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +2
            objWriter.WriteLine(TextBox76.Text & "_" & TextBox1.Text & " (+2)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox71.Text & "_" & TextBox70.Text & "_" & TextBox69.Text & "_" & TextBox68.Text & "_" & TextBox67.Text & "_" & TextBox66.Text & "_" & TextBox65.Text & "_" & TextBox64.Text & "_" & TextBox63.Text & "_" & TextBox62.Text & "_" & TextBox61.Text & "_" & TextBox236.Text & "_" & TextBox235.Text & "_" & TextBox234.Text & "_" & TextBox9.Text & "_" & TextBox233.Text & "_" & TextBox232.Text & "_" & TextBox231.Text & "_" & TextBox230.Text & "_" & TextBox229.Text & "_" & TextBox228.Text & "_" & TextBox227.Text & "_" & TextBox226.Text & "_" & TextBox225.Text & "_" & TextBox224.Text & "_" & TextBox223.Text & "_" & TextBox222.Text & "_" & TextBox221.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +3
            objWriter.WriteLine(TextBox92.Text & "_" & TextBox1.Text & " (+3)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox87.Text & "_" & TextBox86.Text & "_" & TextBox85.Text & "_" & TextBox84.Text & "_" & TextBox83.Text & "_" & TextBox82.Text & "_" & TextBox81.Text & "_" & TextBox80.Text & "_" & TextBox79.Text & "_" & TextBox78.Text & "_" & TextBox77.Text & "_" & TextBox252.Text & "_" & TextBox251.Text & "_" & TextBox250.Text & "_" & TextBox9.Text & "_" & TextBox249.Text & "_" & TextBox248.Text & "_" & TextBox247.Text & "_" & TextBox246.Text & "_" & TextBox245.Text & "_" & TextBox244.Text & "_" & TextBox243.Text & "_" & TextBox242.Text & "_" & TextBox241.Text & "_" & TextBox240.Text & "_" & TextBox239.Text & "_" & TextBox238.Text & "_" & TextBox237.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +4
            objWriter.WriteLine(TextBox108.Text & "_" & TextBox1.Text & " (+4)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox103.Text & "_" & TextBox102.Text & "_" & TextBox101.Text & "_" & TextBox100.Text & "_" & TextBox99.Text & "_" & TextBox98.Text & "_" & TextBox97.Text & "_" & TextBox96.Text & "_" & TextBox95.Text & "_" & TextBox94.Text & "_" & TextBox93.Text & "_" & TextBox268.Text & "_" & TextBox267.Text & "_" & TextBox266.Text & "_" & TextBox9.Text & "_" & TextBox265.Text & "_" & TextBox264.Text & "_" & TextBox263.Text & "_" & TextBox262.Text & "_" & TextBox261.Text & "_" & TextBox260.Text & "_" & TextBox259.Text & "_" & TextBox258.Text & "_" & TextBox257.Text & "_" & TextBox256.Text & "_" & TextBox255.Text & "_" & TextBox254.Text & "_" & TextBox253.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +5
            objWriter.WriteLine(TextBox124.Text & "_" & TextBox1.Text & " (+5)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox119.Text & "_" & TextBox118.Text & "_" & TextBox117.Text & "_" & TextBox116.Text & "_" & TextBox115.Text & "_" & TextBox114.Text & "_" & TextBox113.Text & "_" & TextBox112.Text & "_" & TextBox111.Text & "_" & TextBox110.Text & "_" & TextBox109.Text & "_" & TextBox284.Text & "_" & TextBox283.Text & "_" & TextBox282.Text & "_" & TextBox9.Text & "_" & TextBox281.Text & "_" & TextBox280.Text & "_" & TextBox279.Text & "_" & TextBox278.Text & "_" & TextBox277.Text & "_" & TextBox276.Text & "_" & TextBox275.Text & "_" & TextBox274.Text & "_" & TextBox273.Text & "_" & TextBox272.Text & "_" & TextBox271.Text & "_" & TextBox270.Text & "_" & TextBox269.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +6
            objWriter.WriteLine(TextBox140.Text & "_" & TextBox1.Text & " (+6)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox135.Text & "_" & TextBox134.Text & "_" & TextBox133.Text & "_" & TextBox132.Text & "_" & TextBox131.Text & "_" & TextBox130.Text & "_" & TextBox129.Text & "_" & TextBox128.Text & "_" & TextBox127.Text & "_" & TextBox126.Text & "_" & TextBox125.Text & "_" & TextBox300.Text & "_" & TextBox299.Text & "_" & TextBox298.Text & "_" & TextBox9.Text & "_" & TextBox297.Text & "_" & TextBox296.Text & "_" & TextBox295.Text & "_" & TextBox294.Text & "_" & TextBox293.Text & "_" & TextBox292.Text & "_" & TextBox291.Text & "_" & TextBox290.Text & "_" & TextBox289.Text & "_" & TextBox288.Text & "_" & TextBox287.Text & "_" & TextBox286.Text & "_" & TextBox285.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +7
            objWriter.WriteLine(TextBox156.Text & "_" & TextBox1.Text & " (+7)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox151.Text & "_" & TextBox150.Text & "_" & TextBox149.Text & "_" & TextBox148.Text & "_" & TextBox147.Text & "_" & TextBox146.Text & "_" & TextBox145.Text & "_" & TextBox144.Text & "_" & TextBox143.Text & "_" & TextBox142.Text & "_" & TextBox141.Text & "_" & TextBox316.Text & "_" & TextBox315.Text & "_" & TextBox314.Text & "_" & TextBox9.Text & "_" & TextBox313.Text & "_" & TextBox312.Text & "_" & TextBox311.Text & "_" & TextBox310.Text & "_" & TextBox309.Text & "_" & TextBox308.Text & "_" & TextBox307.Text & "_" & TextBox306.Text & "_" & TextBox305.Text & "_" & TextBox304.Text & "_" & TextBox303.Text & "_" & TextBox302.Text & "_" & TextBox301.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +8
            objWriter.WriteLine(TextBox172.Text & "_" & TextBox1.Text & " (+8)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox167.Text & "_" & TextBox166.Text & "_" & TextBox165.Text & "_" & TextBox164.Text & "_" & TextBox163.Text & "_" & TextBox162.Text & "_" & TextBox161.Text & "_" & TextBox160.Text & "_" & TextBox159.Text & "_" & TextBox158.Text & "_" & TextBox157.Text & "_" & TextBox332.Text & "_" & TextBox331.Text & "_" & TextBox330.Text & "_" & TextBox9.Text & "_" & TextBox329.Text & "_" & TextBox328.Text & "_" & TextBox327.Text & "_" & TextBox326.Text & "_" & TextBox325.Text & "_" & TextBox324.Text & "_" & TextBox323.Text & "_" & TextBox322.Text & "_" & TextBox321.Text & "_" & TextBox320.Text & "_" & TextBox319.Text & "_" & TextBox318.Text & "_" & TextBox317.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +9
            objWriter.WriteLine(TextBox188.Text & "_" & TextBox1.Text & " (+9)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & TextBox183.Text & "_" & TextBox182.Text & "_" & TextBox181.Text & "_" & TextBox180.Text & "_" & TextBox179.Text & "_" & TextBox178.Text & "_" & TextBox177.Text & "_" & TextBox176.Text & "_" & TextBox175.Text & "_" & TextBox174.Text & "_" & TextBox173.Text & "_" & TextBox348.Text & "_" & TextBox347.Text & "_" & TextBox346.Text & "_" & TextBox9.Text & "_" & TextBox345.Text & "_" & TextBox344.Text & "_" & TextBox343.Text & "_" & TextBox342.Text & "_" & TextBox341.Text & "_" & TextBox340.Text & "_" & TextBox339.Text & "_" & TextBox338.Text & "_" & TextBox337.Text & "_" & TextBox336.Text & "_" & TextBox335.Text & "_" & TextBox334.Text & "_" & TextBox333.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            'Item_ext Line +10
            objWriter.WriteLine(TextBox204.Text & "_" & TextBox1.Text & " (+10)" & "_" & TextBox2.Text & "_" & TextBox3.Text & "_" & TextBox14.Text & "_" & TextBox4.Text & "_" & TextBox5.Text & "_" & ComboBox2.SelectedIndex & "_" & TextBox6.Text & "_" & TextBox15.Text & "_" & TextBox16.Text & "_" & TextBox8.Text & "_" & TextBox7.Text & "_" & TextBox17.Text & "_" & "," & TextBox199.Text & "_" & TextBox198.Text & "_" & TextBox197.Text & "_" & TextBox196.Text & "_" & TextBox195.Text & "_" & TextBox194.Text & "_" & TextBox193.Text & "_" & TextBox192.Text & "_" & TextBox191.Text & "_" & TextBox190.Text & "_" & TextBox189.Text & "_" & TextBox364.Text & "_" & TextBox363.Text & "_" & TextBox362.Text & "_" & TextBox9.Text & "_" & TextBox361.Text & "_" & TextBox360.Text & "_" & TextBox359.Text & "_" & TextBox358.Text & "_" & TextBox357.Text & "_" & TextBox356.Text & "_" & TextBox355.Text & "_" & TextBox354.Text & "_" & TextBox353.Text & "_" & TextBox352.Text & "_" & TextBox351.Text & "_" & TextBox350.Text & "_" & TextBox349.Text & "_" & TextBox10.Text & "_" & TextBox11.Text & "_" & TextBox12.Text & "_" & ComboBox3.SelectedIndex & "_" & ComboBox4.SelectedIndex & ")")
            objWriter.Close()
        Catch ex As Exception
            MsgBox("Item_ext file has been updated!")
        Finally
            MsgBox("Item_ext has been created!")
        End Try

        Me.Hide()
        Form4.Show()

    End Sub

    Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click

        Me.Hide()
        Form3.Show()

    End Sub
End Class